import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import { Suspense } from "react";
import FullSpinner from "@/ui/fullSpinner";
import { ClerkProvider } from "@clerk/nextjs";
import StoreProvider from "@/state/StoreProvider";

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Gollis-tournament",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' data-theme='dark'>
      <body
        className={`${quicksand.variable} antialiased text-green-200 overflow-x-hidden`}
      >
        <ClerkProvider>
          <StoreProvider>
            <Suspense fallback={<FullSpinner />}>
              <main>{children}</main>
            </Suspense>
            <Toaster />
          </StoreProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
